/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { format, isSameMonth } from "date-fns";
import { ptBR } from "date-fns/locale";
import { AlertTriangle, CalendarClock, CheckCircle2, Pencil, Plus, Search, Trash2, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

const CATEGORIES=["Aluguel","Água","Energia","Internet","Marketing","Produtos","Funcionários","Impostos","Equipamentos","Manutenção","Outros"];
const CENTERS=["Administrativo","Recepção","Marketing","Estoque","Serviços","Produtos"];
const STATUS:any={pending:["Pendente","secondary"],due_today:["Vence hoje","default"],overdue:["Vencida","destructive"],partially_paid:["Parcialmente paga","outline"],paid:["Paga","secondary"],cancelled:["Cancelada","outline"]};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
type Expense={id:string;description:string;amount:number;paid_amount:number;category:string|null;supplier:string|null;cost_center:string|null;notes:string|null;due_date:string;competence_date:string|null;expense_date:string;status:string;installment_number:number|null;installment_count:number|null;recurring_plan_id:string|null};
const empty={description:"",amount:"",category:"Outros",supplier:"",cost_center:"Administrativo",notes:"",due_date:format(new Date(),"yyyy-MM-dd"),competence_date:format(new Date(),"yyyy-MM-dd"),installments:"1"};

export default function Expenses(){
 const {profile,establishmentRole}=useAuth(); const qc=useQueryClient(); const canManage=establishmentRole==="owner"||establishmentRole==="admin"; const isOwner=establishmentRole==="owner";
 const [form,setForm]=useState<any>(empty),[editing,setEditing]=useState<Expense|null>(null),[paying,setPaying]=useState<Expense|null>(null),[busy,setBusy]=useState(false);
 const [payment,setPayment]=useState<any>({date:format(new Date(),"yyyy-MM-dd"),amount:"",method:"pix",account:"Caixa principal",interest:"0",fine:"0",discount:"0",notes:""});
 const [filters,setFilters]=useState<any>({q:"",status:"all",category:"all",supplier:"",center:"all",from:"",to:"",min:"",max:""});
 useEffect(()=>{document.title="Contas a Pagar | Beauty Core"},[]);
 const {data:expenses=[],isLoading}=useQuery<Expense[]>({queryKey:["payables",profile?.id],enabled:!!profile?.id,queryFn:async()=>{const {data,error}=await supabase.from("expenses").select("*").eq("establishment_id",profile.id).is("deleted_at",null).order("due_date" as any);if(error)throw error;return data as any}});
 const rows=useMemo(()=>expenses.filter(e=>{const q=filters.q.toLowerCase();return(!q||e.description.toLowerCase().includes(q)||(e.supplier||"").toLowerCase().includes(q))&&(filters.status==="all"||e.status===filters.status)&&(filters.category==="all"||e.category===filters.category)&&(!filters.supplier||(e.supplier||"").toLowerCase().includes(filters.supplier.toLowerCase()))&&(filters.center==="all"||e.cost_center===filters.center)&&(!filters.from||e.due_date>=filters.from)&&(!filters.to||e.due_date<=filters.to)&&(!filters.min||e.amount>=+filters.min)&&(!filters.max||e.amount<=+filters.max)}),[expenses,filters]);
 const totals=useMemo(()=>({open:expenses.filter(e=>!["paid","cancelled"].includes(e.status)).reduce((s,e)=>s+e.amount-e.paid_amount,0),paid:expenses.filter(e=>e.status==="paid"&&isSameMonth(new Date(e.due_date+"T12:00:00"),new Date())).reduce((s,e)=>s+e.paid_amount,0),overdue:expenses.filter(e=>e.status==="overdue").reduce((s,e)=>s+e.amount-e.paid_amount,0),today:expenses.filter(e=>e.status==="due_today").length}),[expenses]);
 const invalidate=()=>{qc.invalidateQueries({queryKey:["payables",profile?.id]});qc.invalidateQueries({queryKey:["reports"]});qc.invalidateQueries({queryKey:["cash-flow"]})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!canManage)return;setBusy(true);try{const data={...form,amount:Number(form.amount)};const {error}=editing?await (supabase as any).rpc("update_payable",{p_id:editing.id,p_changes:data}):await (supabase as any).rpc("create_payables",{p_establishment:profile.id,p_data:data,p_installments:Number(form.installments||1)});if(error)throw error;toast.success(editing?"Despesa atualizada.":"Conta a pagar criada.");setEditing(null);setForm(empty);invalidate()}catch(x:any){toast.error(x.message)}finally{setBusy(false)}};
 const openEdit=(e:Expense)=>{setEditing(e);setForm({...empty,...e,amount:String(e.amount),installments:String(e.installment_count||1)})};
 const doPay=async()=>{if(!paying)return;setBusy(true);try{const {error}=await (supabase as any).rpc("pay_expense",{p_id:paying.id,p_payment_date:payment.date,p_amount:Number(payment.amount),p_method:payment.method,p_account:payment.account,p_interest:Number(payment.interest||0),p_fine:Number(payment.fine||0),p_discount:Number(payment.discount||0),p_notes:payment.notes||null});if(error)throw error;toast.success("Pagamento registrado e fluxo de caixa atualizado.");setPaying(null);invalidate()}catch(x:any){toast.error(x.message)}finally{setBusy(false)}};
 const remove=async(e:Expense)=>{if(!isOwner||!confirm(`Excluir “${e.description}”? Movimentações relacionadas também serão removidas.`))return;const {error}=await (supabase as any).rpc("delete_payable",{p_id:e.id});if(error)toast.error(error.message);else{toast.success("Despesa excluída.");invalidate()}};
 const F=({label,k,type="text"}:{label:string;k:string;type?:string})=><div className="space-y-1"><Label>{label}</Label><Input type={type} value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>;
 return <div className="min-h-screen bg-background"><header className="border-b bg-card"><div className="container mx-auto px-4 py-6"><h1 className="text-2xl font-bold">Contas a Pagar</h1><p className="text-muted-foreground">Do previsto à quitação, com integração automática ao fluxo de caixa</p></div></header><main className="container mx-auto px-4 py-6 space-y-5">
  <div className="grid gap-3 grid-cols-2 lg:grid-cols-4"><Metric title="Total em aberto" value={money(totals.open)} icon={WalletCards}/><Metric title="Pago no mês" value={money(totals.paid)} icon={CheckCircle2}/><Metric title="Total vencido" value={money(totals.overdue)} icon={AlertTriangle}/><Metric title="Vencem hoje" value={String(totals.today)} icon={CalendarClock}/></div>
  {canManage&&<Card><CardHeader><CardTitle className="flex gap-2"><Plus className="h-5 w-5"/>{editing?"Editar despesa":"Nova conta a pagar"}</CardTitle></CardHeader><CardContent><form onSubmit={save} className="grid md:grid-cols-4 gap-3"><div className="md:col-span-2"><F label="Descrição" k="description"/></div><F label="Fornecedor" k="supplier"/><F label="Valor total" k="amount" type="number"/><div className="space-y-1"><Label>Categoria</Label><Select value={form.category} onValueChange={v=>setForm({...form,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{CATEGORIES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label>Centro de custo</Label><Select value={form.cost_center} onValueChange={v=>setForm({...form,cost_center:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{CENTERS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><F label="Competência" k="competence_date" type="date"/><F label="Vencimento" k="due_date" type="date"/>{!editing&&<F label="Parcelas" k="installments" type="number"/>}<div className="md:col-span-3 space-y-1"><Label>Observações</Label><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="md:col-span-4 flex gap-2"><Button disabled={busy}>{busy?"Salvando...":"Salvar"}</Button>{editing&&<Button type="button" variant="outline" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</Button>}</div></form></CardContent></Card>}
  <Card><CardHeader><CardTitle>Contas</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Descrição ou fornecedor" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/></div><Select value={filters.status} onValueChange={v=>setFilters({...filters,status:v})}><SelectTrigger><SelectValue placeholder="Status"/></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem>{Object.entries(STATUS).map(([k,v]:any)=><SelectItem value={k} key={k}>{v[0]}</SelectItem>)}</SelectContent></Select><Select value={filters.category} onValueChange={v=>setFilters({...filters,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas as categorias</SelectItem>{CATEGORIES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Input placeholder="Filtrar fornecedor" value={filters.supplier} onChange={e=>setFilters({...filters,supplier:e.target.value})}/><Input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><Input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/><Input type="number" placeholder="Valor mínimo" value={filters.min} onChange={e=>setFilters({...filters,min:e.target.value})}/><Input type="number" placeholder="Valor máximo" value={filters.max} onChange={e=>setFilters({...filters,max:e.target.value})}/></div>
   {isLoading?<p>Carregando...</p>:rows.length===0?<p className="text-sm text-muted-foreground py-6 text-center">Nenhuma conta encontrada.</p>:<div className="space-y-2">{rows.map(e=>{const st=STATUS[e.status]||STATUS.pending;const balance=e.amount-e.paid_amount;return <div key={e.id} className="rounded-lg border p-3 flex flex-col md:flex-row md:items-center gap-3"><div className="flex-1 min-w-0"><div className="flex flex-wrap gap-2 items-center"><b>{e.description}</b><Badge variant={st[1]}>{st[0]}</Badge>{e.installment_count&&e.installment_count>1&&<Badge variant="outline">{e.installment_number}/{e.installment_count}</Badge>}</div><p className="text-xs text-muted-foreground mt-1">Vence {format(new Date(e.due_date+"T12:00:00"),"dd 'de' MMMM",{locale:ptBR})} · {e.supplier||"Sem fornecedor"} · {e.category||"Sem categoria"} · {e.cost_center||"Sem centro"}</p>{e.paid_amount>0&&<p className="text-xs mt-1">Pago {money(e.paid_amount)} · Saldo {money(balance)}</p>}</div><div className="font-bold text-destructive">{money(e.amount)}</div>{canManage&&<div className="flex gap-1">{!["paid","cancelled"].includes(e.status)&&<Button size="sm" onClick={()=>{setPaying(e);setPayment({...payment,amount:String(balance)})}}>Pagar</Button>}{(e.status!=="paid"||isOwner)&&<Button size="icon" variant="ghost" onClick={()=>openEdit(e)}><Pencil className="h-4 w-4"/></Button>}{isOwner&&<Button size="icon" variant="ghost" onClick={()=>remove(e)}><Trash2 className="h-4 w-4"/></Button>}</div>}</div>})}</div>}</CardContent></Card>
 </main>
 <Dialog open={!!paying} onOpenChange={v=>!v&&setPaying(null)}><DialogContent><DialogHeader><DialogTitle>Registrar pagamento</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3"><PayField label="Data" k="date" type="date" p={payment} set={setPayment}/><PayField label="Valor da dívida" k="amount" type="number" p={payment} set={setPayment}/><PayField label="Juros" k="interest" type="number" p={payment} set={setPayment}/><PayField label="Multa" k="fine" type="number" p={payment} set={setPayment}/><PayField label="Desconto" k="discount" type="number" p={payment} set={setPayment}/><div className="space-y-1"><Label>Forma de pagamento</Label><Select value={payment.method} onValueChange={v=>setPayment({...payment,method:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["pix","dinheiro","boleto","transferência","cartão"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="col-span-2"><PayField label="Conta financeira" k="account" p={payment} set={setPayment}/></div><div className="col-span-2"><PayField label="Observações" k="notes" p={payment} set={setPayment}/></div><p className="col-span-2 text-sm font-medium">Saída realizada: {money(Number(payment.amount||0)+Number(payment.interest||0)+Number(payment.fine||0)-Number(payment.discount||0))}</p></div><DialogFooter><Button variant="outline" onClick={()=>setPaying(null)}>Cancelar</Button><Button disabled={busy} onClick={doPay}>Confirmar pagamento</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
function Metric({title,value,icon:Icon}:any){return <Card><CardContent className="pt-5 flex justify-between"><div><p className="text-xs text-muted-foreground">{title}</p><p className="text-xl font-bold mt-1">{value}</p></div><Icon className="h-5 w-5 text-primary"/></CardContent></Card>}
function PayField({label,k,p,set,type="text"}:any){return <div className="space-y-1"><Label>{label}</Label><Input type={type} step={type==="number"?"0.01":undefined} value={p[k]} onChange={e=>set({...p,[k]:e.target.value})}/></div>}
