// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-appointments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-appointments.ts
var list_appointments_default = defineTool({
  name: "list_appointments",
  title: "List appointments",
  description: "List appointments for the signed-in salon within a date range (defaults to today).",
  inputSchema: {
    start_date: z.string().describe("ISO date/time lower bound (inclusive). Defaults to today 00:00.").optional(),
    end_date: z.string().describe("ISO date/time upper bound (exclusive). Defaults to tomorrow 00:00.").optional(),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const now = /* @__PURE__ */ new Date();
    const start = start_date ?? new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString();
    const end = end_date ?? new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1).toISOString();
    const { data, error } = await supabaseForUser(ctx).from("appointments").select("id, start_time, end_time, status, notes, client_id, professional_id, service_id").gte("start_time", start).lt("start_time", end).order("start_time", { ascending: true }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "List clients",
  description: "List salon clients, optionally filtered by a search term matching name, phone, or email.",
  inputSchema: {
    search: z2.string().describe("Optional search term (name, phone, email).").optional(),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("clients").select("id, name, phone, email, birth_date, notes").order("name", { ascending: true }).limit(limit ?? 50);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`name.ilike.${s},phone.ilike.${s},email.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_services_default = defineTool3({
  name: "list_services",
  title: "List services",
  description: "List services offered by the signed-in salon (name, price, duration).",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("services").select("id, name, price, duration_minutes, active").order("name", { ascending: true }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gikjhasawuhylrpchfqv";
var mcp_default = defineMcp({
  name: "salaopro-mcp",
  title: "SalaoPro MCP",
  version: "0.1.0",
  instructions: "Tools for the SalaoPro salon management app. Use list_appointments to read the salon agenda, list_clients to look up customers, and list_services to see the salon's service catalog. All calls are scoped to the signed-in user's salon.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_appointments_default, list_clients_default, list_services_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
