// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqkqpaizbrzqkqhsfnzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxa3FwYWl6YnJ6cWtxaHNmbnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDUwMjQsImV4cCI6MjA3MDMyMTAyNH0.XD809PDftrccRjsYkDacQdHRpVAJqppyo3Eb5gHSOG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});